3821B1FI2/1_permutations_cxx/kazantsev_evgeny/permutations_cxx.cpp
3821B1FI2/1_permutations_cxx/kazantsev_evgeny/permutations_cxx.h
3821B1FI2/2_integral_oneapi/kazantsev_evgeny/integral_oneapi.cpp
3821B1FI2/2_integral_oneapi/kazantsev_evgeny/integral_oneapi.h
3821B1FI2/3_jacobi_acc_oneapi/kazantsev_evgeny/jacobi_acc_oneapi.cpp
3821B1FI2/3_jacobi_acc_oneapi/kazantsev_evgeny/jacobi_acc_oneapi.h
3821B1FI2/4_jacobi_dev_oneapi/kazantsev_evgeny/jacobi_dev_oneapi.cpp
3821B1FI2/4_jacobi_dev_oneapi/kazantsev_evgeny/jacobi_dev_oneapi.h
3821B1FI2/5_jacobi_shared_oneapi/kazantsev_evgeny/jacobi_shared_oneapi.cpp
3821B1FI2/5_jacobi_shared_oneapi/kazantsev_evgeny/jacobi_shared_oneapi.h
3821B1FI2/6_gemm_block_oneapi/kazantsev_evgeny/gemm_block_oneapi.cpp
3821B1FI2/6_gemm_block_oneapi/kazantsev_evgeny/gemm_block_oneapi.h
3821B1FI2/7_gemm_mkl_oneapi/kazantsev_evgeny/gemm_mkl_oneapi.cpp
3821B1FI2/7_gemm_mkl_oneapi/kazantsev_evgeny/gemm_mkl_oneapi.h

Tasks 1-7. Kazantsev Evgeny. 3821Б1Фи2

---

3821B1FI3/3_jacobi_acc_oneapi/kulagin_aleksandr/jacobi_acc_oneapi.cpp
3821B1FI3/3_jacobi_acc_oneapi/kulagin_aleksandr/main.cpp

Task 3. Кулагин Александр 3821Б1ФИ3. Potential fix 1.

---

3821B1FI3/3_jacobi_acc_oneapi/kulagin_aleksandr/jacobi_acc_oneapi.cpp
3821B1FI3/3_jacobi_acc_oneapi/kulagin_aleksandr/main.cpp

I get it now. I swapped result buffers but I forgot to swap result vectors. I was just unlucky to only get even number of iterations in which the bug wasn't present.

Task 3. Кулагин Александр 3821Б1ФИ3. Potential fix 3.

---

3821B1FI3/6_gemm_block_oneapi/kulagin_aleksandr/gemm_block_oneapi.cpp

The block size has been reduced. I hope this will fix everything.

Task 6. Кулагин Александр 3821Б1ФИ3. Potential fix 1.

---

3821B1FI2/1_permutations_cxx/zawadowski_jan/permutations_cxx.cpp
3821B1FI2/1_permutations_cxx/zawadowski_jan/permutations_cxx.h

Zawadowski Jan. 3821B1FI2. Task 1

---

3821B1FI2/2_integral_oneapi/zawadowski_jan/integral_oneapi.cpp
3821B1FI2/2_integral_oneapi/zawadowski_jan/integral_oneapi.h

Zawadowski Jan. 3821B1FI2. Task 2

---

3821B1FI2/3_jacobi_acc_oneapi/zawadowski_jan/jacobi_acc_oneapi.cpp
3821B1FI2/3_jacobi_acc_oneapi/zawadowski_jan/jacobi_acc_oneapi.h

Zawadowski Jan. 3821B1FI2. Task 3

---

3821B1FI2/4_jacobi_dev_oneapi/zawadowski_jan/jacobi_dev_oneapi.cpp
3821B1FI2/4_jacobi_dev_oneapi/zawadowski_jan/jacobi_dev_oneapi.h

Zawadowski Jan. 3821B1FI2. Task 4

---

3821B1FI2/5_jacobi_shared_oneapi/zawadowski_jan/jacobi_shared_oneapi.cpp
3821B1FI2/5_jacobi_shared_oneapi/zawadowski_jan/jacobi_shared_oneapi.h

Zawadowski Jan. 3821B1FI2. Task 5

---

3821B1FI2/6_gemm_block_oneapi/zawadowski_jan/gemm_block_oneapi.cpp
3821B1FI2/6_gemm_block_oneapi/zawadowski_jan/gemm_block_oneapi.h

Zawadowski Jan. 3821B1FI2. Task 6

---

3821B1FI2/7_gemm_mkl_oneapi/zawadowski_jan/gemm_mkl_oneapi.cpp
3821B1FI2/7_gemm_mkl_oneapi/zawadowski_jan/gemm_mkl_oneapi.h

Zawadowski Jan. 3821B1FI2. Task 7

---

3821B1FI3/1_permutations_cxx/volodin_evgeniy/permutations_cxx.cpp
3821B1FI3/1_permutations_cxx/volodin_evgeniy/permutations_cxx.h

Function ```Permutations``` has been implemented.

Task #1 - Permutations. Volodin Evgeniy, 3821B1FI3

---

3821B1FI3/2_integral_oneapi/volodin_evgeniy/integral_oneapi.cpp
3821B1FI3/2_integral_oneapi/volodin_evgeniy/integral_oneapi.h

Function ```IntegralONEAPI``` has been implemented.

Task #2 - Integral. Volodin Evgeniy, 3821B1FI3

---

3821B1FI3/3_jacobi_acc_oneapi/volodin_evgeniy/jacobi_acc_oneapi.cpp
3821B1FI3/3_jacobi_acc_oneapi/volodin_evgeniy/jacobi_acc_oneapi.h

Function ```JacobiAccONEAPI``` has been implemented.

Task #3 - JacobiAcc. Volodin Evgeniy, 3821B1FI3

---

3821B1FI3/5_jacobi_shared_oneapi/volodin_evgeniy/jacobi_shared_oneapi.cpp
3821B1FI3/5_jacobi_shared_oneapi/volodin_evgeniy/jacobi_shared_oneapi.h

Function ```JacobiSharedONEAPI``` has been implemented.

Task #5 - JacobiShared. Volodin Evgeniy, 3821B1FI3

---

3821B1FI3/6_gemm_block_oneapi/volodin_evgeniy/gemm_block_oneapi.cpp
3821B1FI3/6_gemm_block_oneapi/volodin_evgeniy/gemm_block_oneapi.h

Function ```GemmBlockONEAPI``` has been implemented.

Task #6 - GemmBlock. Volodin Evgeniy, 3821B1FI3

---

3821B1FI3/7_gemm_mkl_oneapi/volodin_evgeniy/gemm_mkl_oneapi.cpp
3821B1FI3/7_gemm_mkl_oneapi/volodin_evgeniy/gemm_mkl_oneapi.h

Function ```GemmMklONEAPI``` has been implemented.

Task #7 - GemmMkl. Volodin Evgeniy, 3821B1FI3

---

3821B1FI3/1_permutations_cxx/safronov_mikhail/permutations_cxx.cpp
3821B1FI3/1_permutations_cxx/safronov_mikhail/permutations_cxx.h
3821B1FI3/2_integral_oneapi/safronov_mikhail/integral_oneapi.cpp
3821B1FI3/2_integral_oneapi/safronov_mikhail/integral_oneapi.h
3821B1FI3/3_jacobi_acc_oneapi/safronov_mikhail/jacobi_acc_oneapi.cpp
3821B1FI3/3_jacobi_acc_oneapi/safronov_mikhail/jacobi_acc_oneapi.h
3821B1FI3/4_jacobi_dev_oneapi/safronov_mikhail/jacobi_dev_oneapi.cpp
3821B1FI3/4_jacobi_dev_oneapi/safronov_mikhail/jacobi_dev_oneapi.h
3821B1FI3/5_jacobi_shared_oneapi/safronov_mikhail/jacobi_shared_oneapi.cpp
3821B1FI3/5_jacobi_shared_oneapi/safronov_mikhail/jacobi_shared_oneapi.h
3821B1FI3/6_gemm_block_oneapi/safronov_mikhail/gemm_block_oneapi.cpp
3821B1FI3/6_gemm_block_oneapi/safronov_mikhail/gemm_block_oneapi.h
3821B1FI3/7_gemm_mkl_oneapi/safronov_mikhail/gemm_mkl_oneapi.cpp
3821B1FI3/7_gemm_mkl_oneapi/safronov_mikhail/gemm_mkl_oneapi.h

Safronov Mikhail, 3821B1FI3, 1-7

---

3821B1FI3/1_permutations_cxx/safarov_nurlan/permutations_cxx.cpp
3821B1FI3/1_permutations_cxx/safarov_nurlan/permutations_cxx.h

There is a set of strings, each string is unique and contains small English letters only. The goal is to make a dictionary of permutations — for each string in a set one should find all other strings from the same set that are permutations of this string.

Safarov Nurlan. 3821B1FI3. Task №1

---

3821B1FI3/3_jacobi_acc_oneapi/safarov_nurlan/jacobi_acc_oneapi.cpp
3821B1FI3/3_jacobi_acc_oneapi/safarov_nurlan/jacobi_acc_oneapi.h

Implement a function solving a system of linear equations by the Jacobi method using SYCL (buffers and accessories). The algorithm must support two stopping criteria:
Termination of calculations if the maximum difference between solutions on neighboring iterations becomes less than the specified accuracy. Automatic stop after 1024 iterations if the accuracy is not reached.

Safarov Nurlan. 3821B1FI3. Task №3

---

3821B1FI3/5_jacobi_shared_oneapi/safarov_nurlan/jacobi_shared_oneapi.cpp
3821B1FI3/5_jacobi_shared_oneapi/safarov_nurlan/jacobi_shared_oneapi.h

This task assumes Jacobi method implementation using SYCL shared memory approach.

Safarov Nurlan. 3821B1FI3. Task №5

---

3821B1FI3/7_gemm_mkl_oneapi/safarov_nurlan/gemm_mkl_oneapi.cpp
3821B1FI3/7_gemm_mkl_oneapi/safarov_nurlan/gemm_mkl_oneapi.h

Let's try to use one of the MKL BLAS APIs to implement general matrix multiplication in the most efficient way.
Each matrix must be stored in a linear array by rows, so that a.size()==size*suze. Function takes two matricies and their size as inputs, and returns result matrix also stored by rows.
For simplicity, let's consider matrix size is always power of 2 and all matricies are square.

Safarov Nurlan. 3821B1FI3. Task №7

---

3821B1FI3/2_integral_oneapi/volodin_evgeniy/integral_oneapi.cpp

Header cmath has been included.

Task #2 (FIX) - Integral. Volodin Evgeniy, 3821B1FI3

---

3821B1FI3/3_jacobi_acc_oneapi/volodin_evgeniy/jacobi_acc_oneapi.cpp

Function JacobiAccONEAPI has been rewroten.

Task #3 (FIX) - JacobiAcc. Volodin Evgeniy, 3821B1FI3

---

3821B1FI3/4_jacobi_dev_oneapi/volodin_evgeniy/jacobi_dev_oneapi.cpp

Task #4 (FIX) - JacobiDev. Volodin Evgeniy, 3821B1FI3
